name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get timestamp
      id: timestamp
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ steps.timestamp.outputs.tag }}

    - name: Run Docker container
      run: docker run -d --name my-container --memory=4g my-image-name:${{ steps.timestamp.outputs.tag }}

    - name: Run TabPy
      run: |
        docker exec my-container tabpy --port=9004 &

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update
        sudo apt-get install ngrok

    - name: Authenticate ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ngrok authtoken $NGROK_TOKEN

    - name: Expose TabPy with ngrok
      run: ngrok http 9004

    - name: Get ngrok public URL
      id: ngrok
      run: |
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
        echo "::set-output name=ngrok_url::$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)"

    - name: Display ngrok URL
      run: echo "TabPy is accessible via ${{ steps.ngrok.outputs.ngrok_url }}"
